// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-about.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var BASE = "https://www.senthilnagappan.com";
var get_about_default = defineTool({
  name: "get_about",
  title: "Get about / positioning",
  description: "Return the public 'about' summary for Senthil Nagappan \u2014 positioning, disciplines, and leadership pillars \u2014 for hiring managers or AI assistants asking who he is and what he does.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const payload = {
      name: "Senthil Nagappan",
      primary_positioning: "AI Experience Design & Human Systems Integration for regulated environments (healthcare, federal, accessibility).",
      disciplines: [
        "AI experience design (human\u2013AI interaction, explainability, HITL)",
        "AI governance & model-risk UX (NIST AI RMF, EU AI Act, ISO 42001)",
        "Design systems at scale (50M+ users in program scope)",
        "Accessibility governance (WCAG 2.2 AAA, Section 508, CPACC)"
      ],
      leadership_pillars: [
        "Player-coach leadership",
        "Mentorship & team growth (scaled team to 15+)",
        "Cross-product systems thinking",
        "Executive & regulator readiness",
        "AI in the design process",
        "Culture of experimentation"
      ],
      portfolio_url: BASE,
      note: "In-House AI Product Lab entries (TrustLens, Clarity, Sentinel, Lumen, RevAssist, WCAG AI Remediation Suite) are self-initiated concepts, not shipped products."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-case-studies.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var BASE2 = "https://www.senthilnagappan.com";
var CASES = [
  {
    id: "ssa",
    title: "A Data-Driven Design System That Unified 50M+ User Experiences",
    category: "Design Systems",
    role: "Design systems lead (Leidos / SSA program scope)",
    summary: "Consolidated fragmented federal experiences into one unified visual system and accessible component library serving 50M+ users.",
    outcomes: [
      "Unified visual language across multiple SSA product lines",
      "AAA-oriented accessible components adopted org-wide",
      "30\u201340% fewer UI defects reported downstream"
    ],
    url: `${BASE2}/#case-ssa`
  },
  {
    id: "clinicalai",
    title: "Clarity \u2014 Explainable Clinical AI Decision-Support",
    category: "AI Experience Design",
    role: "Lead designer (self-initiated concept)",
    summary: "Concept product for oversight-tiered clinical AI: calibrated confidence, human-in-the-loop escalation, and audit-ready override capture for 1,200+ clinicians in the reference scenario.",
    outcomes: [
      "Recommend / act / alert oversight tiers by model risk",
      "Confidence and rationale surfaced instead of raw probabilities",
      "Every override captured as regulator-ready evidence"
    ],
    url: `${BASE2}/#case-clinicalai`,
    inHouseLab: true
  },
  {
    id: "ge",
    title: "Evolving a Design System to Power Consistent, Accessible Digital Experiences",
    category: "Design Systems",
    role: "Senior design systems contributor (GE HealthCare program scope)",
    summary: "Evolved a healthcare design system for cross-product consistency, accessibility, and faster shipping across a large product portfolio.",
    outcomes: [
      "Shared token + component foundation across product teams",
      "Accessibility built into the system, not bolted on",
      "Faster time-to-ship for new product surfaces"
    ],
    url: `${BASE2}/#case-ge`
  },
  {
    id: "trustlens",
    title: "TrustLens \u2014 AI Governance & Model-Risk Command Center",
    category: "AI Governance",
    role: "Product designer (self-initiated concept)",
    summary: "Concept command center for AI governance mapped to NIST AI RMF, EU AI Act, and ISO 42001 \u2014 model cards, drift monitoring, and audit-ready evidence.",
    outcomes: [
      "Governance mapped to real regulatory frameworks",
      "Drift and bias monitoring surfaced at portfolio level",
      "Audit packages assembled as an export, not a fire drill"
    ],
    url: `${BASE2}/#case-trustlens`,
    inHouseLab: true
  },
  {
    id: "bestbuy",
    title: "Driving Engagement for 1M+ Consumers Through Cohesive Digital Brand Experiences",
    category: "Brand & Experience",
    role: "Experience designer (Best Buy program scope)",
    summary: "Cohesive digital brand experience work for a national retail audience, driving engagement across acquisition and loyalty surfaces.",
    outcomes: [
      "Unified brand expression across web and app",
      "Improved engagement for 1M+ consumers in program scope",
      "Reusable patterns adopted across marketing surfaces"
    ],
    url: `${BASE2}/#case-bestbuy`
  },
  {
    id: "samhsa",
    title: "$130M Federal Behavioral Health Program",
    category: "Federal / HSI",
    role: "Design lead (federal program scope)",
    summary: "Human Systems Integration and accessible experience design for a national behavioral-health program supporting people in crisis.",
    outcomes: [
      "Safe-state design for high-stakes user journeys",
      "AAA accessibility across the primary user surfaces",
      "Federal data-submitter workflows redesigned for clarity"
    ],
    url: `${BASE2}/#case-samhsa`
  },
  {
    id: "wcagtool",
    title: "WCAG AI Remediation Suite",
    category: "Accessibility \xB7 AI",
    role: "Product designer (self-initiated concept)",
    summary: "AAA-compliant remediation engine that pairs static analysis with AI suggestions, visual cues, and one-click fixes for accessibility issues.",
    outcomes: [
      "Portfolio-level accessibility dashboard",
      "AI suggestions grounded in WCAG success criteria",
      "Suggested fixes surfaced with visual before/after cues"
    ],
    url: `${BASE2}/#case-wcagtool`,
    inHouseLab: true
  },
  {
    id: "sentinel",
    title: "Sentinel \u2014 Guardrails & Red-Team Console for Agentic AI",
    category: "AI Safety",
    role: "Product designer (self-initiated concept)",
    summary: "Concept console for agentic AI safety: live action ledger, high-impact approval gates, and red-team scenarios that contain prompt-injection attempts.",
    outcomes: [
      "Every agent action visible in a live ledger",
      "High-impact actions pause for human approval",
      "Prompt-injection scenarios caught and contained"
    ],
    url: `${BASE2}/#case-sentinel`,
    inHouseLab: true
  },
  {
    id: "lumen",
    title: "Lumen \u2014 Source-Grounding & Transparency UX for Enterprise Knowledge AI",
    category: "RAG / Knowledge AI",
    role: "Product designer (self-initiated concept)",
    summary: "Concept RAG interface with traceable citations, a source inspector, and an insufficient-evidence state that refuses to fabricate.",
    outcomes: [
      "Grounded answers with per-claim citations",
      "Source inspector for evidence verification",
      "Explicit 'insufficient evidence' state to prevent hallucination"
    ],
    url: `${BASE2}/#case-lumen`,
    inHouseLab: true
  },
  {
    id: "revcycle",
    title: "RevAssist \u2014 AI-Assisted Revenue Cycle & Reimbursement Workspace",
    category: "Healthcare AI",
    role: "Product designer (self-initiated concept)",
    summary: "AI-assisted revenue-cycle workspace concept: coding suggestions, denial prediction, and reimbursement workflows with human-in-the-loop review.",
    outcomes: [
      "Suggested codes with confidence + rationale",
      "Denial risk surfaced before submission",
      "Human review as the default for high-impact edits"
    ],
    url: `${BASE2}/#case-revcycle`,
    inHouseLab: true
  }
];
var IDS = CASES.map((c) => c.id);
var get_case_studies_default = defineTool2({
  name: "get_case_studies",
  title: "Get case studies",
  description: "Return public portfolio case studies for Senthil Nagappan. Pass an optional id to fetch a single case, or a category to filter. Each case includes title, role, summary, outcomes, and a link to the full write-up.",
  inputSchema: {
    id: z.string().optional().describe(`Optional case id. One of: ${IDS.join(", ")}.`),
    category: z.string().optional().describe(
      "Optional category filter, e.g. 'AI Experience Design', 'Design Systems', 'AI Governance', 'AI Safety'. Case-insensitive substring match."
    ),
    in_house_lab_only: z.boolean().optional().describe("If true, return only self-initiated In-House AI Product Lab concepts.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id, category, in_house_lab_only }) => {
    let items = CASES;
    if (id) items = items.filter((c) => c.id === id);
    if (category) {
      const q = category.toLowerCase();
      items = items.filter((c) => c.category.toLowerCase().includes(q));
    }
    if (in_house_lab_only) items = items.filter((c) => c.inHouseLab);
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { count: items.length, cases: items }
    };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var BASE3 = "https://www.senthilnagappan.com";
var get_contact_info_default = defineTool3({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Return public ways to contact Senthil Nagappan: portfolio site, contact section, and r\xE9sum\xE9 link. Use this when a caller asks how to reach out, book a call, or hire.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const payload = {
      name: "Senthil Nagappan",
      portfolio_url: BASE3,
      contact_section_url: `${BASE3}/#contact`,
      resume_pdf_url: `${BASE3}/Senthil_Nagappan_Resume.pdf`,
      availability: "Selectively taking on senior/director AI experience design & design leadership engagements.",
      note: "Use the contact section on the portfolio site for the fastest response."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-resume.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var BASE4 = "https://www.senthilnagappan.com";
var get_resume_default = defineTool4({
  name: "get_resume",
  title: "Get r\xE9sum\xE9",
  description: "Return the public download URL for Senthil Nagappan's r\xE9sum\xE9 (PDF) along with a short profile summary.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const payload = {
      name: "Senthil Nagappan",
      headline: "AI Experience Design & Human Systems Integration for regulated environments",
      resume_pdf_url: `${BASE4}/Senthil_Nagappan_Resume.pdf`,
      portfolio_url: BASE4,
      credentials: [
        "CPACC",
        "WCAG 2.2 AAA",
        "NIST AI RMF",
        "FDA / IEC 62366",
        "DoDI 5000.95"
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-skills-matrix.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var LEVEL_LABEL = ["", "Aware", "Working", "Proficient", "Advanced", "Expert"];
var GROUPS = [
  {
    id: "ai-product",
    title: "AI Product & Interaction Design",
    blurb: "Designing the surface where people and models meet \u2014 legible, controllable, trustworthy.",
    skills: [
      { name: "Human\u2013AI interaction patterns", level: 5, note: "recommend / act / alert oversight models" },
      { name: "Explainability & confidence UX", level: 5, note: "calibrated trust, not raw percentages" },
      { name: "Human-in-the-loop & escalation", level: 5, note: "graceful degradation, safe states" },
      { name: "Agentic AI & tool-use UX", level: 4, note: "guardrails, approvals, action transparency" },
      { name: "RAG & source-grounding UX", level: 4, note: "citations, evidence linking, hallucination cues" },
      { name: "Prompt & conversation design", level: 4, note: "structured prompting, system instructions" }
    ]
  },
  {
    id: "ai-frameworks",
    title: "Governance Frameworks & Standards",
    blurb: "Translating dense AI, medical, and federal standards into enforceable design and delivery criteria.",
    skills: [
      { name: "NIST AI RMF 1.0", level: 5, note: "govern / map / measure / manage" },
      { name: "EU AI Act", level: 4, note: "risk tiers, prohibited & high-risk obligations" },
      { name: "ISO/IEC 42001 & 23894", level: 4, note: "AI management systems, risk guidance" },
      { name: "FDA / IEC 62366 usability", level: 5, note: "medical-device human-factors engineering" },
      { name: "WCAG 2.2 & Section 508", level: 5, note: "AA/AAA accessibility conformance" },
      { name: "DoDI 5000.95 & MIL-STD-1472H", level: 4, note: "Human Systems Integration standards" }
    ]
  },
  {
    id: "ai-operations",
    title: "Operational Governance & Evaluation",
    blurb: "Making compliance a built-in property \u2014 oversight tiers, audit evidence, and quality gates.",
    skills: [
      { name: "Model risk & oversight tiers", level: 5, note: "Model A/B/C governance at design intake" },
      { name: "Human-in-the-loop approval gates", level: 5, note: "override capture, full audit logging" },
      { name: "Audit-ready evidence packages", level: 5, note: "traceable proof captured as a byproduct" },
      { name: "Bias, fairness & drift monitoring", level: 4, note: "material-change alerts, fairness charts" },
      { name: "TEVV & red-team evaluation", level: 4, note: "test, evaluation, verification, validation" },
      { name: "CI/CD compliance quality gates", level: 4, note: "checks at commit, not post-deploy" }
    ]
  },
  {
    id: "ai-regulated",
    title: "Regulated-Domain Expertise",
    blurb: "Governing safety-critical AI where getting it wrong isn't an option \u2014 healthcare, federal, accessibility.",
    skills: [
      { name: "Clinical decision-support AI", level: 5, note: "1,200+ clinicians, oversight-tiered design" },
      { name: "Federal / DoD programs", level: 5, note: "HSI, national-scale behavioral-health systems" },
      { name: "Accessibility governance programs", level: 5, note: "org-wide policy across product lines" },
      { name: "Regulatory evidence & traceability", level: 5, note: "every control mapped to a standard" },
      { name: "Safe-state & failure-mode design", level: 4, note: "graceful degradation for high-stakes calls" },
      { name: "Executive & board readiness", level: 4, note: "regulator-ready governance readouts" }
    ]
  },
  {
    id: "ai-engineering",
    title: "AI Engineering & Delivery",
    blurb: "Building the front end that makes AI systems usable \u2014 accessible, performant, shipped.",
    skills: [
      { name: "AI data-viz component systems", level: 5, note: "risk gauges, model cards, audit timelines" },
      { name: "LLM integration (React + TS)", level: 4, note: "streaming, state, error handling" },
      { name: "CI/CD AI quality gates", level: 4, note: "SSA11y \u2014 checks at commit, not post-deploy" },
      { name: "Llama / GPT-class model use", level: 4, note: "pattern detection, suggested fixes" },
      { name: "Accessible AI interfaces", level: 5, note: "WCAG 2.2 AA/AAA, colorblind-safe charts" },
      { name: "Eval harness & telemetry UX", level: 4, note: "dashboards for model behavior over time" }
    ]
  }
];
var get_skills_matrix_default = defineTool5({
  name: "get_skills_matrix",
  title: "Get AI skills matrix",
  description: "Return Senthil Nagappan's AI skills matrix. Groups cover AI product & interaction design, governance frameworks, operational governance, regulated-domain expertise, and AI engineering. Levels are 1\u20135 (Aware \u2192 Expert). Optionally filter to a single group.",
  inputSchema: {
    group_id: z2.string().optional().describe(
      "Optional group id: ai-product, ai-frameworks, ai-operations, ai-regulated, ai-engineering."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ group_id }) => {
    const items = group_id ? GROUPS.filter((g) => g.id === group_id) : GROUPS;
    const withLabels = items.map((g) => ({
      ...g,
      skills: g.skills.map((s) => ({ ...s, level_label: LEVEL_LABEL[s.level] }))
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(withLabels, null, 2) }],
      structuredContent: { legend: LEVEL_LABEL.slice(1), groups: withLabels }
    };
  }
});

// src/lib/mcp/tools/search-case-studies.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
var search_case_studies_default = defineTool6({
  name: "search_case_studies",
  title: "Search case studies",
  description: "Search Senthil Nagappan's portfolio case studies by keyword. Matches against title, summary, category, role, and outcomes (case-insensitive). Returns matching titles, summaries, and URLs.",
  inputSchema: {
    query: z3.string().min(1).describe("Keyword or phrase to search for across case study title, summary, category, role, and outcomes."),
    limit: z3.number().int().positive().optional().describe("Optional maximum number of results to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, limit }) => {
    const q = query.toLowerCase().trim();
    const matches = CASES.filter((c) => {
      const haystack = [
        c.title,
        c.summary,
        c.category,
        c.role,
        ...c.outcomes ?? []
      ].join(" \n ").toLowerCase();
      return haystack.includes(q);
    }).map((c) => ({
      id: c.id,
      title: c.title,
      summary: c.summary,
      url: c.url,
      category: c.category,
      inHouseLab: c.inHouseLab ?? false
    }));
    const results = typeof limit === "number" ? matches.slice(0, limit) : matches;
    return {
      content: [
        {
          type: "text",
          text: results.length === 0 ? `No case studies matched "${query}".` : JSON.stringify(results, null, 2)
        }
      ],
      structuredContent: { query, count: results.length, results }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "senthil-nagappan-portfolio",
  title: "Senthil Nagappan \xB7 Portfolio",
  version: "0.1.0",
  instructions: "Public read-only tools exposing Senthil Nagappan's portfolio: case studies, keyword search, AI skills matrix, r\xE9sum\xE9 link, contact info, and about/positioning. All data is already public on senthilnagappan.com. Use these to answer hiring-manager questions, summarize experience, or link back to full write-ups.",
  tools: [get_case_studies_default, search_case_studies_default, get_skills_matrix_default, get_about_default, get_resume_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
